-- MySQL Script generated by MySQL Workbench
-- Wed Aug 10 11:17:59 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema peluqueria_canina
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema peluqueria_canina
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `peluqueria_canina` DEFAULT CHARACTER SET utf8 ;
USE `peluqueria_canina` ;

-- -----------------------------------------------------
-- Table `peluqueria_canina`.`Dueno`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`Dueno` (
  `DNI` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Apellido` VARCHAR(45) NULL,
  `Telefono` VARCHAR(45) NULL,
  `Dirección` VARCHAR(45) NULL,
  PRIMARY KEY (`DNI`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peluqueria_canina`.`Perro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`Perro` (
  `ID_Perro` INT NOT NULL,
  `Nombre` VARCHAR(45) NOT NULL,
  `Fecha_nac` DATETIME NULL,
  `Sexo` VARCHAR(45) NULL,
  `DNI_Dueno` INT NOT NULL,
  PRIMARY KEY (`ID_Perro`),
   CONSTRAINT `fk_Perro_Dueno`
    FOREIGN KEY (`DNI_Dueno`)
    REFERENCES `Dueno` (`DNI`)
    )
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `peluqueria_canina`.`Historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `peluqueria_canina`.`Historial` (
  `ID_Historial` INT NOT NULL,
  `Fecha` DATETIME NULL,
  `Descripcion` VARCHAR(255) NULL,
  `Monto` DECIMAL NULL,
  `Perro` INT NOT NULL,
  PRIMARY KEY (`ID_Historial`),
  
  CONSTRAINT `fk_Historial_Perro1`
    FOREIGN KEY (`Perro`)
    REFERENCES `Perro` (`ID_Perro`)
    )
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
